[package]
name = "termchat"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
crossterm = { version = "0.20.0", default-features = false }
structopt = { version = "0.3", default-features = false }
