[package]
name = "direct_rest"
version = "0.1.0"
authors = ["Mark <mverleg.noreply@gmail.com>"]

[dependencies]
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
simple-server = "0.3.0"

[[bin]]
name = 'server'
path = 'src/rest_server/server.rs'

[[bin]]
name = 'client'
path = 'src/main.rs'
